### ISSUE TITLE
junos_install_os not supported on new srx300 series

### ISSUE THREAD

**Issue by epydd** [Juniper/ansible-junos-stdlib#222]
After trying to upgrade a SRX320, an exception is raised:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_If0wkf/ansible_module_junos_install_os.py", line 307, in <module>
    main()
  File "/tmp/ansible_If0wkf/ansible_module_junos_install_os.py", line 292, in main
    results = junos_install_os(module, dev)
  File "/tmp/ansible_If0wkf/ansible_module_junos_install_os.py", line 221, in junos_install_os
    ok = sw.install(package, **sw_args)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 678, in install
    **kwargs)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 176, in pkgadd
    rsp = self.rpc.request_package_add(**args)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/rpcmeta.py", line 156, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 71, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 18, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/device.py", line 585, in execute
    raise e(cmd=rpc_cmd_e, rsp=rsp, errs=err)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: command is not valid on the srx320)
```

Im using:
junos-eznc (2.1.1)
Juniper.junos, 1.4.0

**Comment by stacywsmith** [comment]
@epydd Can you please provide the version of Junos currently running on your SRX320, and the full name of the image you are trying to install with `junos_install_os`? In addition, can you provide the full contents of your playbook?

**Comment by epydd** [comment]
Current version on SRX320:
```
root@E0> show version
Hostname: E0
Model: srx320
Junos: 15.1X49-D75.5
JUNOS Software Release [15.1X49-D75.5]
```

Full name:
`junos-srxsme-15.1X49-D80.4-domestic.tgz`

Playbook:
```
- name: Upgrading Junos
  hosts: "{{ Cluster }}"
  gather_facts: no
  connection: local
  roles:
    - Juniper.junos
  vars_files:
    - "vars/ZTP.yml"
  tasks:

    - name: Getting Junos version
      junos_command:
        host: "{{ inventory_hostname }}"
        rpcs: "get-software-information"
      register: junos_version

    - debug:
        msg: "{{ junos_version.stdout[0]['software-information']['junos-version'] }}"

    - name: Install Junos OS package
      junos_install_os:
        logfile: "{{ inventory_hostname }}.log"
        host: "{{ inventory_hostname }}"
        version: "15.1X49-D80.4"
        package: "/var/ftp/junos-srxsme-15.1X49-D80.4-domestic.tgz"
        no_copy: true
      register: junos_upgrade
      notify:
        - wait_reboot

    - debug:
        msg: "{{ junos_upgrade }}"

  handlers:
    - name: wait_reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 600
      when: not junos_upgrade.check_mode
```

**Comment by vnitinv** [comment]
@epydd Can you share the output of below cli

```request system software add junos-srxsme-15.1X49-D80.4-domestic.tgz | display xml rpc```

**Comment by epydd** [comment]
@vnitinv  Heres the output
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <rpc>
        <request-package-add>
                <package-name>junos-srxsme-15.1X49-D80.4-domestic.tgz</package-name>
        </request-package-add>
    </rpc>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>

**Comment by stacywsmith** [comment]
I have an update on this issue...

I have recreated this issue on an SRX320 and captured the following NETCONF traceoptions showing the problematic RPC:
```
Apr 13 17:23:22 [3750] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:7be38bca-91f9-4394-98b6-6a45042e1f86"><request-package-add><no-validate/><re0/><package-name>/var/tmp/junos-srxsme-15.1X49-D80.4-domestic.tgz</package-name></request-package-add></nc:rpc>]]>]]>
Apr 13 17:23:26 [3750] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:7be38bca-91f9-4394-98b6-6a45042e1f86">
Apr 13 17:23:26 [3750] Outgoing: <rpc-error>
Apr 13 17:23:26 [3750] Outgoing: <error-type>protocol</error-type>
Apr 13 17:23:26 [3750] Outgoing: <error-tag>operation-failed</error-tag>
Apr 13 17:23:26 [3750] Outgoing: <error-severity>error</error-severity>
Apr 13 17:23:26 [3750] Outgoing: <error-message>
Apr 13 17:23:26 [3750] Outgoing: command is not valid on the srx320
Apr 13 17:23:26 [3750] Outgoing: </error-message>
Apr 13 17:23:26 [3750] Outgoing: </rpc-error>
Apr 13 17:23:26 [3750] Outgoing: </rpc-reply>
Apr 13 17:23:26 [3750] Outgoing: ]]>]]>
Apr 13 17:23:26 [3750] Outgoing: <!-- session end at 2017-04-13 17:23:26 PDT -->
```

I believe it is the `<re0/>` argument which is causing the RPC to fail. Based on this cli output with `| display xml rpc` it appears the `<no-validate/>` and `<package-name>` elements are valid:
```
user@srx320> request system software add no-validate /var/tmp/junos-srxsme-15.1X49-D80.4-domestic.tgz | display xml rpc                       
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <rpc>
        <request-package-add>
                <no-validate/>
                <package-name>/var/tmp/junos-srxsme-15.1X49-D80.4-domestic.tgz</package-name>
        </request-package-add>
    </rpc>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

I will continue to investigate why the `<re0/>` argument is being added to the RPC.
