### ISSUE TITLE
Not able to instal ansible-galaxy 

### ISSUE THREAD

**Issue by farhadkam** [Juniper/ansible-junos-stdlib#362]
I am getting this error installing ansible-galaxy anyone can help me?
Thanks.
```MSYDI:~ farhad$ sudo ansible-galaxy install Juniper.junos
Password:
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 146, in <module>
    display.error("Unexpected Exception, this is probably a bug: %s" % to_text(e), wrap_text=False)
  File "/Library/Python/2.7/site-packages/ansible/utils/display.py", line 290, in error
    self.display(new_msg, color=C.COLOR_ERROR, stderr=True)
  File "/Library/Python/2.7/site-packages/ansible/utils/display.py", line 137, in display
    msg2 = to_bytes(msg2, encoding=self._output_encoding(stderr=stderr))
  File "/Library/Python/2.7/site-packages/ansible/module_utils/_text.py", line 133, in to_bytes
    return obj.encode(encoding, errors)
LookupError: unknown encoding: 
MSYDI:~ farhad$```

**Comment by farhadkam** [comment]
I added these environmental variables and the problem was solved.

$ export LANG=en_US.UTF-8  
$ export LC_ALL=en_US.UTF-8
