### ISSUE TITLE
junos_install_config giving name error in ansible 2.5

### ISSUE THREAD

**Issue by adolphsons** [Juniper/ansible-junos-stdlib#371]
Issue Type
------

 - Bug Report

Module Name
------

Juniper.Junos role and Python libraries version

```
Juniper.junos version 1.4.3

ansible 2.5.2
  config file = /tftpboot/vSRX/ansible/ansible.cfg
  configured module search path = [u'/tftpboot/vSRX/ansible/.plugins/action']
  ansible python module location = /opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible
  executable location = /opt/rh/python27/root/usr/bin/ansible
  python version = 2.7.13 (default, Feb  8 2017, 06:30:30) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

pip freeze
ansible==2.5.2
asn1crypto==0.24.0
bcrypt==3.1.4
bigsuds==1.0.6
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
cryptography==2.2.2
enum34==1.1.6
f5-icontrol-rest==1.3.8
f5-sdk==3.0.14
idna==2.6
ipaddress==1.0.22
Jinja2==2.10
junos-eznc==2.1.7
junos-netconify==1.0.2
lxml==4.2.0
MarkupSafe==1.0
ncclient==0.5.3
netaddr==0.7.19
paramiko==2.4.1
pexpect==4.4.0
ptyprocess==0.5.2
pyasn1==0.4.2
pycontrol==2.1
pycparser==2.18
pycrypt==0.7.2
PyNaCl==1.2.1
pyserial==3.4
PyYAML==3.12
requests==2.18.4
scp==0.10.2
six==1.11.0
suds==0.4
suds-jurko==0.6
urllib3==1.22
```

OS / Environment
------

```
Model: vsrx
Junos: 15.1X49-D100.6
JUNOS Software Release [15.1X49-D100.6]
```
Summary
------

Since upgrading from ansible 2.4 to 2.5.2, we are experiencing errors when running the junos_install_config module with a set file. 

Steps to reproduce
------

```yaml
---
- name: Implement the set configs via the config file
  junos_install_config:
    host: "{{hostname}}"
    user: "{{ user }}"
    port: 22
    passwd: "{{ passwd }}"
    file: "{{current_dir}}/srx_config.set"
    overwrite: no
    comment: "configured by Ansible for ticket {{ comment }}"
```

Expected results

```
TASK [vSRX : Implement the set configs via the config file] ****************************************************************************************************
changed: [vSRX-01]
```
Actual results
------

```
TASK [vSRX : Implement the set configs via the config file] ****************************************************************************************************
task path: /tftpboot/vSRX/ansible/roles/vSRX/tasks/implement_set_config.yml:2
Using module file /tftpboot/vSRX/ansible/roles/Juniper.junos/library/junos_install_config
<vSRX-01> ESTABLISH LOCAL CONNECTION FOR USER: ab1234
<vSRX-01> EXEC /bin/sh -c 'echo ~ab1234 && sleep 0'
<vSRX-01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ab1234/.ansible/tmp/ansible-tmp-1527635539.42-241357433013109 `" && echo ansible-tmp-1527635539.42-241357433013109="` echo /home/ab1234/.ansible/tmp/ansible-tmp-1527635539.42-241357433013109 `" ) && sleep 0'
<vSRX-01> PUT /home/ab1234/.ansible/tmp/ansible-local-151290LxHtO/tmpEbwEFV TO /home/ab1234/.ansible/tmp/ansible-tmp-1527635539.42-241357433013109/junos_install_config
<vSRX-01> EXEC /bin/sh -c 'chmod u+x /home/ab1234/.ansible/tmp/ansible-tmp-1527635539.42-241357433013109/ /home/ab1234/.ansible/tmp/ansible-tmp-1527635539.42-241357433013109/junos_install_config && sleep 0'
<vSRX-01> EXEC /bin/sh -c '/usr/bin/env python /home/ab1234/.ansible/tmp/ansible-tmp-1527635539.42-241357433013109/junos_install_config && sleep 0'
<vSRX-01> EXEC /bin/sh -c 'rm -f -r /home/ab1234/.ansible/tmp/ansible-tmp-1527635539.42-241357433013109/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_dPQp4t/ansible_module_junos_install_config.py", line 521, in <module>
    main()
  File "/tmp/ansible_dPQp4t/ansible_module_junos_install_config.py", line 489, in main
    overwrite=dict(required=False, type='bool', choices=BOOLEANS, default=False),
NameError: global name 'BOOLEANS' is not defined
fatal: [vSRX-01]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_dPQp4t/ansible_module_junos_install_config.py\", line 521, in <module>\n    main()\n  File \"/tmp/ansible_dPQp4t/ansible_module_junos_install_config.py\", line 489, in main\n    overwrite=dict(required=False, type='bool', choices=BOOLEANS, default=False),\nNameError: global name 'BOOLEANS' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

**Comment by stacywsmith** [comment]
> Juniper.junos version 1.4.3

Please upgrade to the latest (2.0.2) release of this role.

**Comment by adolphsons** [comment]
Is there known bugs that would cause this?

**Comment by rahkumar651991** [comment]
This is a very old issue, marking it as inactive. From the comments, it should have been resolved by upgradation.

**Comment by rahkumar651991** [comment]
closing this due to inactivity
