### ISSUE TITLE
juniper_junos_common.py write XML output errors with "AttributeError: 'bytes' object has no attribute 'encode'"

### ISSUE THREAD

**Issue by omegafoo** [Juniper/ansible-junos-stdlib#411]
Issue Type
------
- Bug Report
 
Module Name
------
Juniper.Junos role and Python libraries version

```
$ ansible --version
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jmn7047/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]

$ pip freeze
ansible==2.7.4
apturl==0.5.2
asn1crypto==0.24.0
bcrypt==3.1.4
beautifulsoup4==4.6.0
blinker==1.4
Brlapi==0.6.6
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
checkbox-support==0.22
click==6.7
command-not-found==0.3
coreapi==2.3.3
coreschema==0.0.4
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
distro-info==0.18
Django==2.0.8
django-cors-headers==2.4.0
django-debug-toolbar==1.9.1
django-filter==1.1.0
django-js-asset==1.1.0
django-mptt==0.9.1
django-tables2==1.21.2
django-taggit==0.22.2
django-taggit-serializer==0.1.7
django-timezone-field==2.1
djangorestframework==3.8.1
drf-yasg==1.9.2
feedparser==5.2.1
flex==6.13.2
future==0.16.0
graphviz==0.8.4
guacamole==0.9.2
gunicorn==19.9.0
html5lib==0.999999999
httplib2==0.9.2
idna==2.6
inflection==0.3.1
itypes==1.1.0
Jinja2==2.10
jsonpointer==1.14
jsonschema==2.6.0
junos-eznc==2.2.0
jxmlease==1.0.2.dev1
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.5.0
lxml==4.2.1
macaroonbakery==1.1.3
Mako==1.0.7
Markdown==2.6.11
MarkupSafe==1.0
natsort==5.3.3
ncclient==0.6.0
netaddr==0.7.19
netifaces==0.10.4
oauth==1.0.1
oauthlib==2.0.6
olefile==0.45.1
onboard==1.4.1
openapi-codec==1.3.2
padme==1.1.1
paramiko==2.4.1
pexpect==4.2.1
Pillow==5.2.0
plainbox==0.25
protobuf==3.0.0
psycopg2-binary==2.7.5
py-gfm==0.1.3
pyasn1==0.4.2
pycairo==1.16.2
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.6.4
pycups==1.9.73
pycurl==7.43.0.1
pygobject==3.26.1
PyJWT==1.5.3
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparsing==2.2.0
pyRFC3339==1.0
pyserial==3.4
python-apt==1.6.3
python-debian==0.1.32
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
rfc3987==1.3.8
ruamel.yaml==0.15.66
scp==0.10.2
SecretStorage==2.3.1
simplejson==3.13.2
six==1.11.0
sqlparse==0.2.4
ssh-import-id==5.7
strict-rfc3339==0.7
swagger-spec-validator==2.4.0
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
uritemplate==3.0.0
urllib3==1.22
usb-creator==0.3.3
validate-email==1.3
wadllib==1.3.2
webencodings==0.5
xdiagnose==3.8.8
xkit==0.0.0
XlsxWriter==0.9.6
xmltodict==0.11.0
zope.interface==4.3.2

$ ansible-galaxy list
- Juniper.junos, 2.1.0

```

OS / Environment
------
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Juniper EX3400 : JUNOS 18.1R3.3

Summary
------
When running a basic playbook to retrieve the display interfaces output from an EX3400 in XML format there is an error writing to the output file. Code is written for Python 2.x and the system is running 3.x

Steps to reproduce
------

```
interfaces.yaml
---
- name: Display Interfaces
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  
  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no
      
    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - name: get interface information
      juniper_junos_rpc:
        rpcs:
          - get-interface-information
        dest_dir: './output'
        return_output: no
        formats: xml
        provider:
          host: "{{ ansible_host }}"
          user: "{{ username }}"
          passwd: "{{ password }}"
      register: interfaces

    - name: display interfaces
      debug:
        var: interfaces


######

ansible-playbook command:

ansible-playbook -i /ansible/inventory interfaces.yaml -vvv

```

Expected results

XML output is to be written to the output defined *.xml file.
```
TASK [get interface information] *******************************************************************************************************************************************************************************************************************************
task path: /ansible/playbooks/juniper/interfaces.yaml:11
<host1.domain.local> ESTABLISH LOCAL CONNECTION FOR USER: jmn7047
<host1.domain.local> EXEC /bin/sh -c 'echo ~jmn7047 && sleep 0'
<host1.domain.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jmn7047/.ansible/tmp/ansible-tmp-1547732370.261537-45401073147181 `" && echo ansible-tmp-1547732370.261537-45401073147181="` echo /home/jmn7047/.ansible/tmp/ansible-tmp-1547732370.261537-45401073147181 `" ) && sleep 0'
Using module file /home/jmn7047/.ansible/roles/Juniper.junos/library/juniper_junos_rpc.py
<host1.domain.local> PUT /home/jmn7047/.ansible/tmp/ansible-local-32346uenau35n/tmpwc3o3uh8 TO /home/jmn7047/.ansible/tmp/ansible-tmp-1547732370.261537-45401073147181/AnsiballZ_juniper_junos_rpc.py
<host1.domain.local> EXEC /bin/sh -c 'chmod u+x /home/jmn7047/.ansible/tmp/ansible-tmp-1547732370.261537-45401073147181/ /home/jmn7047/.ansible/tmp/ansible-tmp-1547732370.261537-45401073147181/AnsiballZ_juniper_junos_rpc.py && sleep 0'
<host1.domain.local> EXEC /bin/sh -c '/usr/bin/python3 /home/jmn7047/.ansible/tmp/ansible-tmp-1547732370.261537-45401073147181/AnsiballZ_juniper_junos_rpc.py && sleep 0'
<host1.domain.local> EXEC /bin/sh -c 'rm -f -r /home/jmn7047/.ansible/tmp/ansible-tmp-1547732370.261537-45401073147181/ > /dev/null 2>&1 && sleep 0'
ok: [host1.domain.local] => {
    "attrs": null,
    "changed": false,
    "format": "xml",
    "invocation": {
        "module_args": {
            "attempts": null,
            "attrs": null,
            "baud": null,
            "console": null,
            "dest": null,
            "dest_dir": "./output",
            "filter": null,
            "formats": [
                "xml"
            ],
            "host": "host1.domain.local",
            "kwargs": null,
            "level": null,
            "logdir": null,
            "logfile": null,
            "mode": null,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "return_output": false,
            "rpcs": [
                "get-interface-information"
            ],
            "ssh_config": null,
            "ssh_private_key_file": null,
            "timeout": 30,
            "user": "<switch_user>"
        }
    },
    "kwargs": null,
    "msg": "The RPC executed successfully.",
    "rpc": "get-interface-information"
}

TASK [display interfaces] **************************************************************************************************************************************************************************************************************************************
task path: /ansible/playbooks/juniper/interfaces.yaml:24
ok: [host1.domain.local] => {
    "interfaces": {
        "attrs": null,
        "changed": false,
        "failed": false,
        "format": "xml",
        "kwargs": null,
        "msg": "The RPC executed successfully.",
        "rpc": "get-interface-information"
    }
}
META: ran handlers
META: ran handlers
```
Actual results
------
When running the playbook error-ed out with a Python error as show in the TASK details below.

The problem is due to trying to write the output file with a Python 2.x encode() function and not correctly identifying the current version as Python 3.x. 

A fix for this situation,  and for consideration as to whether it is a permanent fix for the code, is attached in the patch file.
[juniper_junos_common.patch.txt]
(https://github.com/Juniper/ansible-junos-stdlib/files/2768826/juniper_junos_common.patch.txt)

```
TASK [Get interface information] *******************************************************************************************************************************************************************************************************************************
task path: /ansible/playbooks/juniper/interfaces.yaml:20
<host1.domain.local> ESTABLISH LOCAL CONNECTION FOR USER: jmn7047
<host1.domain.local> EXEC /bin/sh -c 'echo ~jmn7047 && sleep 0'
<host1.domain.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814 `" && echo ansible-tmp-1547727751.784292-14811900883814="` echo /home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814 `" ) && sleep 0'
Using module file /home/jmn7047/.ansible/roles/Juniper.junos/library/juniper_junos_rpc.py
<host1.domain.local> PUT /home/jmn7047/.ansible/tmp/ansible-local-31427k9tkg6ea/tmpxgurs86h TO /home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py
<host1.domain.local> EXEC /bin/sh -c 'chmod u+x /home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/ /home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py && sleep 0'
<host1.domain.local> EXEC /bin/sh -c '/usr/bin/python3 /home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py && sleep 0'
<host1.domain.local> EXEC /bin/sh -c 'rm -f -r /home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py", line 113, in <module>
    _ansiballz_main()
  File "/home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_juniper_junos_rpc_payload_vnha89c_/__main__.py", line 622, in <module>
  File "/tmp/ansible_juniper_junos_rpc_payload_vnha89c_/__main__.py", line 600, in main
  File "/tmp/ansible_juniper_junos_rpc_payload_vnha89c_/ansible_juniper_junos_rpc_payload.zip/ansible/module_utils/juniper_junos_common.py", line 1875, in save_text_output
AttributeError: 'bytes' object has no attribute 'encode'

fatal: [host1.domain.local]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jmn7047/.ansible/tmp/ansible-tmp-1547727751.784292-14811900883814/AnsiballZ_juniper_junos_rpc.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_juniper_junos_rpc_payload_vnha89c_/__main__.py\", line 622, in <module>\n  File \"/tmp/ansible_juniper_junos_rpc_payload_vnha89c_/__main__.py\", line 600, in main\n  File \"/tmp/ansible_juniper_junos_rpc_payload_vnha89c_/ansible_juniper_junos_rpc_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 1875, in save_text_output\nAttributeError: 'bytes' object has no attribute 'encode'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by fbettag** [comment]
every pip upgrade i have to apply the patch again :(

**Comment by rsmekala** [comment]
Pull request raised #453
