### ISSUE TITLE
ignore_warning parameter for module juniper_junos_config doesn't work in versions greater than 2.3.1

### ISSUE THREAD

**Issue by avisom** [Juniper/ansible-junos-stdlib#513]
Issue Type
------
 - Bug Report

Module Name
------
juniper_junos_config 

Juniper.Junos role and Python libraries version
```
 ansible --version
ansible 2.8.4
  config file = /home/skipped/.ansible.cfg
  configured module search path = ['/home/skipped/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

ansible-galaxy list
# /home/skipped/.ansible/roles
- Juniper.junos, 2.3.2
# /usr/share/ansible/roles
# /etc/ansible/roles


 pip3 freeze
ansible==2.8.4
ansible-lint==4.1.0
asn1crypto==0.24.0
backcall==0.1.0
bcrypt==3.1.7
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
clickhouse-driver==0.0.20
cryptography==2.7
DateTime==4.3
decorator==4.4.2
dnspython==1.16.0
docopt==0.6.2
entrypoints==0.3
flake8==3.7.8
future==0.17.1
gitdb==4.0.5
GitPython==3.1.3
idna==2.8
ipaddress==1.0.23
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.17.0
Jinja2==2.10.1
jtextfsm==0.3.1
junos-eznc==2.2.1
jxmlease==1.0.1
lxml==4.4.1
MarkupSafe==1.1.1
mccabe==0.6.1
ncclient==0.6.6
netaddr==0.7.19
netmiko==2.4.2
paramiko==2.6.0
paramiko-expect==0.2.8
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
ply==3.11
prompt-toolkit==3.0.5
psycopg2==2.7.7
ptyprocess==0.6.0
pyasn1==0.4.7
pycodestyle==2.5.0
pycparser==2.19
pycryptodomex==3.9.0
pyflakes==2.1.1
Pygments==2.6.1
PyNaCl==1.3.0
pynetbox==4.0.8
pyserial==3.4
pysmi==0.3.4
pysnmp==4.4.11
python-dotenv==0.10.3
pytz==2019.1
PyYAML==5.1.2
redis==3.3.8
requests==2.22.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.1.2
scp==0.13.2
six==1.12.0
smmap==3.0.4
textfsm==1.1.0
traitlets==4.3.3
urllib3==1.25.3
virtualenv==16.7.5
vk-api==11.5.0
wcwidth==0.1.9
xmltodict==0.12.0
zope.interface==4.7.1

```

Summary
------
When using _juniper_junos_config_  with option _ignore_warning_ on versions 2.3.2 and 2.4.0 of Juniper.junos collection got traceback, on 2.3.1 works fine

Steps to reproduce
------
```
ansible-playbook -DC junos.yml -f 30 --limit=EX4300
```
```yaml
- name: JUNOS:REPLACE LOCAL USERS
  juniper_junos_config:
    load: replace
    lines: "{{ lookup('template', 'system_login.j2') }}"
    format: text
    config_mode: exclusive
    diff: true
    check: false
    commit: true
    diffs_file: "~/diffs/junos_{{inventory_hostname}}_local_users_diff.junos"
    comment: replace local users
    port: "22"
    timeout: 180
    ignore_warning:
      - statement not found
  register: response
```

Expected results

```
Working playbook
```
Actual results
------
For example on version 2.3.2
```
Using module file /home/skipped/.ansible/roles/Juniper.junos/library/juniper_junos_config.py
Pipelining is enabled.
<10.253.81.34> ESTABLISH LOCAL CONNECTION FOR USER: skipped
<10.253.81.34> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/usr/lib64/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_juniper_junos_config_payload_ei5_ru11/__main__.py", line 1148, in <module>
  File "/tmp/ansible_juniper_junos_config_payload_ei5_ru11/__main__.py", line 1080, in main
  File "/tmp/ansible_juniper_junos_config_payload_ei5_ru11/ansible_juniper_junos_config_payload.zip/ansible/module_utils/juniper_junos_common.py", line 1573, in diff_configuration
TypeError: diff() got an unexpected keyword argument 'ignore_warning'

fatal: [EX4300]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/usr/lib64/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib64/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_juniper_junos_config_payload_ei5_ru11/__main__.py\", line 1148, in <module>\n  File \"/tmp/ansible_juniper_junos_config_payload_ei5_ru11/__main__.py\", line 1080, in main\n  File \"/tmp/ansible_juniper_junos_config_payload_ei5_ru11/ansible_juniper_junos_config_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 1573, in diff_configuration\nTypeError: diff() got an unexpected keyword argument 'ignore_warning'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by rahkumar651991** [comment]
Hi @avisom  - 
Upgrade junos-eznc(PyEZ) to version 2.5.0. 
Changes have gone related to ignore_warning in both ansible-roles and PyEZ. Recommended to use is juniper.junos (roles) 2.4.0 and junos-eznc(PyEZ) 2.5.0 .
