### ISSUE TITLE
'JuniperJunosModule' object has no attribute 'conn_type'

### ISSUE THREAD

**Issue by a-maxime** [Juniper/ansible-junos-stdlib#560]
Issue Type
------
 - Bug Report

Module Name
------
juniper.device.config

**juniper.device collection and Python libraries version**

```
Maxime$ ansible-galaxy collection list

# /XXX/XXX/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.1.0  
ansible.utils     2.2.0  
juniper.device    1.0.0 
```

```
(pfe_env) Maxime$ ansible --version
ansible 2.10.10
  config file = None
  configured module search path = ['/XXX/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /XXX/XXX/pfe_env/lib/python3.8/site-packages/ansible
  executable location = /XXX/XXX/pfe_env/bin/ansible
  python version = 3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39) [Clang 6.0 (clang-600.0.57)]
```

```
(pfe_env) Maxime$ python -m pip freeze
altgraph==0.17
ansible==4.1.0
ansible-base==2.10.10
ansible-core==2.11.1
ansible-runner==1.4.7
bcrypt==3.2.0
cffi==1.14.5
cryptography==3.4.7
docutils==0.17.1
future==0.18.2
ipaddr==2.2.0
Jinja2==3.0.1
junos-eznc==2.6.1
jxmlease==1.0.3
lockfile==0.12.2
lxml==4.6.3
macholib==1.14
MarkupSafe==2.0.1
modulegraph==0.18
ncclient==0.6.12
netaddr==0.8.0
packaging==20.9
paramiko==2.7.2
pexpect==4.8.0
psutil==5.8.0
ptyprocess==0.7.0
py2app==0.24
pycparser==2.20
pyhpecw7==0.0.11
pyinstaller-hooks-contrib==2021.1
PyNaCl==1.4.0
pyparsing==2.4.7
pyserial==3.5
PySide2==5.15.2
python-daemon==2.3.0
PyYAML==5.4.1
resolvelib==0.5.4
scp==0.13.3
shiboken2==5.15.2
six==1.15.0
textfsm==1.1.0
toml==0.10.2
transitions==0.8.8
xmltodict==0.12.0
yamlordereddictloader==0.4.0
```

OS / Environment
------

JUNOS 14.1X53-D46.7
Ansible Control Node : macOS Mojave 10.14.6 & CentOS 8

Summary
------

On running the playbook below, I get a `'JuniperJunosModule' object has no attribute 'conn_type'` error and I can't figure out why.

Steps to reproduce
------

Inventory
```
[junos]
1.1.1.1 #obviously fake address for online posting

[junos:vars]
ansible_user=foo
ansible_password=foo
ansible_python_interpreter="/XXX/XXX/pfe_env/bin/python"
```

Playbook
```yaml
---
- name: Juniper Playbook
  hosts: junos
  gather_facts: no
  connection: local
  collections:
    - juniper.device

  vars:
    username: foo
    password: foo
    conf: "foo.cfg"
    firmware : "foo.tgz"

  tasks:
    - name: Checking NETCONF connectivity (Timeout 5 minutes)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 300

    - name: Installing Junos OS package
      juniper.device.software:
        reboot: yes
        local_package: "{{ firmware }}"
        user: "{{ user }}"
        password: "{{ password }}"
      register: sw

   - name: DEBUG
     debug:
        var: sw
    
    - name: Wait for reboot if OS changed
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 300
      #when: sw.changed

    - name: Installing configuration
      juniper.device.config:
        src: "{{ conf }}"
        update: "override"
```

Expected results

```
PLAY [Juniper Playbook] **************************************************************************************

TASK [Checking NETCONF connectivity (Timeout 5 minutes)] *****************************************************
ok: [1.1.1.1]

TASK [Installing Junos OS package] ***************************************************************************
ok: [1.1.1.1]

TASK [DEBUG] *************************************************************************************************
ok: [1.1.1.1] => {
    "sw": {
        "changed": false,
        "check_mode": false,
        "failed": false,
        "msg": "Current version on 14.1X53-D46.7: fpc0 same as Targeted version: 14.1X53-D46.7.\n"
    }
}

TASK [Wait for reboot if OS changed] *************************************************************************
ok: [1.1.1.1]

TASK [Installing configuration] ******************************************************************************
ok: [1.1.1.1] **or** changed: [1.1.1.1]

PLAY RECAP ***************************************************************************************************
1.1.1.1                : ok=**5**    changed=**1**    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
Actual results
------

Config module isn't working properly, and return an conn_type error

```
ansible-playbook 2.10.10
  config file = None
  configured module search path = ['/XXX/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /XXX/XXX/pfe_env/lib/python3.8/site-packages/ansible
  executable location = /XXX/XXX/pfe_env/bin/ansible-playbook
  python version = 3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39) [Clang 6.0 (clang-600.0.57)]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /XXX/XXX/Desktop/AnsibleFiles/inventory as it did not pass its verify_file() method
script declined parsing /XXX/XXX/Desktop/AnsibleFiles/inventory as it did not pass its verify_file() method
auto declined parsing /XXX/XXX/Desktop/AnsibleFiles/inventory as it did not pass its verify_file() method
Parsed /XXX/XXX/Desktop/AnsibleFiles/inventory inventory source with ini plugin
Loading collection juniper.device from /XXX/XXX/.ansible/collections/ansible_collections/juniper/device
Loading callback plugin default of type stdout, v2.0 from /XXX/XXX/pfe_env/lib/python3.8/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: JunosAnsible2.yaml *********************************************************************************
Positional arguments: Desktop/AnsibleFiles/JunosAnsible2.yaml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/XXX/XXX/Desktop/AnsibleFiles/inventory',)
forks: 5
1 plays in Desktop/AnsibleFiles/JunosAnsible2.yaml

PLAY [Juniper Playbook] **************************************************************************************
META: ran handlers

TASK [Checking NETCONF connectivity (Timeout 5 minutes)] *****************************************************
task path: /XXX/XXX/Desktop/AnsibleFiles/JunosAnsible2.yaml:16
<1.1.1.1> ESTABLISH LOCAL CONNECTION FOR USER: Maxime
<1.1.1.1> EXEC /bin/sh -c 'echo ~Maxime && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /XXX/XXX/.ansible/tmp `"&& mkdir "` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017383.494333-83278-28512814426579 `" && echo ansible-tmp-1624017383.494333-83278-28512814426579="` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017383.494333-83278-28512814426579 `" ) && sleep 0'
Using module file /XXX/XXX/pfe_env/lib/python3.8/site-packages/ansible/modules/wait_for.py
<1.1.1.1> PUT /XXX/XXX/.ansible/tmp/ansible-local-832746qd9_jm9/tmpkepvk3f4 TO /XXX/XXX/.ansible/tmp/ansible-tmp-1624017383.494333-83278-28512814426579/AnsiballZ_wait_for.py
<1.1.1.1> EXEC /bin/sh -c 'chmod u+x /XXX/XXX/.ansible/tmp/ansible-tmp-1624017383.494333-83278-28512814426579/ /XXX/XXX/.ansible/tmp/ansible-tmp-1624017383.494333-83278-28512814426579/AnsiballZ_wait_for.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '/XXX/XXX/pfe_env/bin/python /XXX/XXX/.ansible/tmp/ansible-tmp-1624017383.494333-83278-28512814426579/AnsiballZ_wait_for.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c 'rm -f -r /XXX/XXX/.ansible/tmp/ansible-tmp-1624017383.494333-83278-28512814426579/ > /dev/null 2>&1 && sleep 0'
ok: [1.1.1.1] => {
    "changed": false,
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "active_connection_states": [
                "ESTABLISHED",
                "FIN_WAIT1",
                "FIN_WAIT2",
                "SYN_RECV",
                "SYN_SENT",
                "TIME_WAIT"
            ],
            "connect_timeout": 5,
            "delay": 0,
            "exclude_hosts": null,
            "host": "1.1.1.1",
            "msg": null,
            "path": null,
            "port": 830,
            "search_regex": null,
            "sleep": 1,
            "state": "started",
            "timeout": 300
        }
    },
    "match_groupdict": {},
    "match_groups": [],
    "path": null,
    "port": 830,
    "search_regex": null,
    "state": "started"
}

TASK [Installing Junos OS package] ***************************************************************************
task path: /XXX/XXX/Desktop/AnsibleFiles/JunosAnsible2.yaml:22
<1.1.1.1> ESTABLISH LOCAL CONNECTION FOR USER: Maxime
<1.1.1.1> EXEC /bin/sh -c 'echo ~Maxime && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /XXX/XXX/.ansible/tmp `"&& mkdir "` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017384.000468-83300-209389117557248 `" && echo ansible-tmp-1624017384.000468-83300-209389117557248="` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017384.000468-83300-209389117557248 `" ) && sleep 0'
Using module file /XXX/XXX/.ansible/collections/ansible_collections/juniper/device/plugins/modules/software.py
<1.1.1.1> PUT /XXX/XXX/.ansible/tmp/ansible-local-832746qd9_jm9/tmp9p0lrxw5 TO /XXX/XXX/.ansible/tmp/ansible-tmp-1624017384.000468-83300-209389117557248/AnsiballZ_software.py
<1.1.1.1> EXEC /bin/sh -c 'chmod u+x /XXX/XXX/.ansible/tmp/ansible-tmp-1624017384.000468-83300-209389117557248/ /XXX/XXX/.ansible/tmp/ansible-tmp-1624017384.000468-83300-209389117557248/AnsiballZ_software.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '/XXX/XXX/pfe_env/bin/python /XXX/XXX/.ansible/tmp/ansible-tmp-1624017384.000468-83300-209389117557248/AnsiballZ_software.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c 'rm -f -r /XXX/XXX/.ansible/tmp/ansible-tmp-1624017384.000468-83300-209389117557248/ > /dev/null 2>&1 && sleep 0'
ok: [1.1.1.1] => {
    "changed": false,
    "check_mode": false,
    "invocation": {
        "module_args": {
            "attempts": null,
            "baud": null,
            "checksum": null,
            "checksum_algorithm": "md5",
            "checksum_timeout": 300,
            "cleanfs_timeout": 300,
            "console": null,
            "cs_passwd": null,
            "cs_user": null,
            "force_host": false,
            "host": "1.1.1.1",
            "issu": false,
            "level": null,
            "logdir": null,
            "logfile": null,
            "mode": null,
            "nssu": false,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "ssh_config": null,
            "ssh_private_key_file": null,
            "timeout": 10,
            "user": "root",
            "validate": false,
            "vmhost": false
        }
    },
    "msg": "Current version on 14.1X53-D46.7: fpc0 same as Targeted version: 14.1X53-D46.7.\n"
}

TASK [DEBUG] *************************************************************************************************
task path: /XXX/XXX/Desktop/AnsibleFiles/JunosAnsible2.yaml:30
ok: [1.1.1.1] => {
    "sw": {
        "changed": false,
        "check_mode": false,
        "failed": false,
        "msg": "Current version on 14.1X53-D46.7: fpc0 same as Targeted version: 14.1X53-D46.7.\n"
    }
}

TASK [Wait for reboot if OS changed] *************************************************************************
task path: /XXX/XXX/Desktop/AnsibleFiles/JunosAnsible2.yaml:34
<1.1.1.1> ESTABLISH LOCAL CONNECTION FOR USER: Maxime
<1.1.1.1> EXEC /bin/sh -c 'echo ~Maxime && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /XXX/XXX/.ansible/tmp `"&& mkdir "` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.430162-83325-22255861703529 `" && echo ansible-tmp-1624017389.430162-83325-22255861703529="` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.430162-83325-22255861703529 `" ) && sleep 0'
Using module file /XXX/XXX/pfe_env/lib/python3.8/site-packages/ansible/modules/wait_for.py
<1.1.1.1> PUT /XXX/XXX/.ansible/tmp/ansible-local-832746qd9_jm9/tmpn_8abdg_ TO /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.430162-83325-22255861703529/AnsiballZ_wait_for.py
<1.1.1.1> EXEC /bin/sh -c 'chmod u+x /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.430162-83325-22255861703529/ /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.430162-83325-22255861703529/AnsiballZ_wait_for.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '/XXX/XXX/pfe_env/bin/python /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.430162-83325-22255861703529/AnsiballZ_wait_for.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c 'rm -f -r /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.430162-83325-22255861703529/ > /dev/null 2>&1 && sleep 0'
ok: [1.1.1.1] => {
    "changed": false,
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "active_connection_states": [
                "ESTABLISHED",
                "FIN_WAIT1",
                "FIN_WAIT2",
                "SYN_RECV",
                "SYN_SENT",
                "TIME_WAIT"
            ],
            "connect_timeout": 5,
            "delay": 0,
            "exclude_hosts": null,
            "host": "1.1.1.1",
            "msg": null,
            "path": null,
            "port": 830,
            "search_regex": null,
            "sleep": 1,
            "state": "started",
            "timeout": 300
        }
    },
    "match_groupdict": {},
    "match_groups": [],
    "path": null,
    "port": 830,
    "search_regex": null,
    "state": "started"
}

TASK [Installing configuration] ******************************************************************************
task path: /XXX/XXX/Desktop/AnsibleFiles/JunosAnsible2.yaml:41
<1.1.1.1> ESTABLISH LOCAL CONNECTION FOR USER: Maxime
<1.1.1.1> EXEC /bin/sh -c 'echo ~Maxime && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /XXX/XXX/.ansible/tmp `"&& mkdir "` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821 `" && echo ansible-tmp-1624017389.734723-83345-13557378440821="` echo /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821 `" ) && sleep 0'
Using module file /XXX/XXX/.ansible/collections/ansible_collections/juniper/device/plugins/modules/config.py
<1.1.1.1> PUT /XXX/XXX/.ansible/tmp/ansible-local-832746qd9_jm9/tmpulcdadq3 TO /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py
<1.1.1.1> EXEC /bin/sh -c 'chmod u+x /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/ /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c '/XXX/XXX/pfe_env/bin/python /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py && sleep 0'
<1.1.1.1> EXEC /bin/sh -c 'rm -f -r /XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py", line 102, in <module>
    _ansiballz_main()
  File "/XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py", line 1164, in <module>
  File "/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py", line 777, in main
  File "/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 570, in __init__
  File "/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible/module_utils/basic.py", line 735, in __init__
  File "/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible/module_utils/basic.py", line 1583, in _check_arguments
  File "/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 722, in fail_json
  File "/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 1163, in close_configuration
AttributeError: 'JuniperJunosModule' object has no attribute 'conn_type'
fatal: [1.1.1.1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/XXX/XXX/.ansible/tmp/ansible-tmp-1624017389.734723-83345-13557378440821/AnsiballZ_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py\", line 1164, in <module>\n  File \"/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py\", line 777, in main\n  File \"/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 570, in __init__\n  File \"/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible/module_utils/basic.py\", line 735, in __init__\n  File \"/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible/module_utils/basic.py\", line 1583, in _check_arguments\n  File \"/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 722, in fail_json\n  File \"/var/folders/sw/vz_csv397yz_hjssfy1r1fk80000gn/T/ansible_juniper.device.config_payload_webo0szi/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 1163, in close_configuration\nAttributeError: 'JuniperJunosModule' object has no attribute 'conn_type'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ***************************************************************************************************
1.1.1.1                : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by rahkumar651991** [comment]
@a-maxime - As multiple tasks have executed successfully, so it seems initial error has been resolved and now the error is in the last task. 

As I can see, "update" is not a valid parameter to be passed for juniper.device.config. The suitable option can be "load: override"  . The error is seen as it can't recognise the parameter passed to the module. The error seen is not explaining it properly, We will take this as input and fix this in next release. 

I would recommend to go through these links for examples and better understanding - 
* https://www.juniper.net/documentation/en_US/junos-ansible/topics/topic-map/junos-ansible-configuration-loading-committing.html
* https://ansible-juniper-collection.readthedocs.io/en/latest/config.html

Let us know, if it resolves your issue.

**Comment by rahkumar651991** [comment]
hi, 
https://github.com/Juniper/ansible-junos-stdlib/pull/564/files will fix the error and show some relevant error. Closing this issue due to inactivity.
