### ISSUE TITLE
RpcTimeoutError while get-checksum-information

### ISSUE THREAD

**Issue by XioNoX** [Juniper/ansible-junos-stdlib#64]
Hi,

After trying to push an upgrade on 3 similar EX2200, I got an error on only one of them:

```
Traceback (most recent call last):
  File "/home/xionox/.ansible/tmp/ansible-tmp-1433407957.74-148018357886798/junos_install_os", line 1867, in <module>
    main()
  File "/home/xionox/.ansible/tmp/ansible-tmp-1433407957.74-148018357886798/junos_install_os", line 255, in main
    results = junos_install_os(module, dev)
  File "/home/xionox/.ansible/tmp/ansible-tmp-1433407957.74-148018357886798/junos_install_os", line 198, in junos_install_os
    ok = sw.install(package, **sw_args)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py", line 385, in install
    checksum=checksum)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py", line 283, in safe_copy
    remote_checksum = self.remote_checksum(remote_package)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py", line 225, in remote_checksum
    rsp = self.rpc.get_checksum_information(path=remote_package)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 137, in _exec_rpc
    return self._junos.execute(rpc)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 25, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 520, in execute
    raise EzErrors.RpcTimeoutError(self, rpc_cmd_e.tag, self.timeout)
jnpr.junos.exception.RpcTimeoutError: RpcTimeoutError(<myswitch>,get-checksum-information,30)
```

Calculating the md5 on the device works fine (and match the original file):
myswitch> file checksum md5 /var/tmp/junos-ex2200-12.3R9-S1.tgz 
MD5 (/var/tmp/junos-ex2200-12.3R9-S1.tgz) = dab7e8ff0cfabcd55c29b94cbf716bbd
the 3 switches are running 11.4.

Please let me know if I can help.

Thanks

**Comment by shermdog** [comment]
Hi @XioNoX,

Thanks for the report.  Looks like we need to bump up the timeout for the checksum RPC.

Did the checksum operation locally seem to take longer than 30 seconds?

Thanks,
-Rick

**Comment by XioNoX** [comment]
Hey,

I've been contacted via email by your colleagues. 
Adding "dev.timeout = 300" after https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_install_os#L249
fixed the issue for me.

Thanks

**Comment by shermdog** [comment]
K.  That confirms the RPC was timing out, but I will modify the behavior on the specific operation in the underlying PyEZ function as that one is expected to take a little longer, which will supersede the global work-around provided.
