### ISSUE TITLE
'JuniperJunosModule' object has no attribute '_pyez_conn'

### ISSUE THREAD

**Issue by emallette** [Juniper/ansible-junos-stdlib#687]
There was a similar bug opened and closed in 2021 (with the same name) but they advised to re-open here.
I also reported in the ansible forum: https://forum.ansible.com/t/tracebacks-attempting-to-collect-facts-from-juniper-acx-7100-32c-device-with-the-juniper-device-collection/7920.

Issue Type
------
 - Bug Report

Module Name
------
```
ansible-galaxy collection list | grep juniper.device
juniper.device 1.0.5
```

```
ansible [core 2.14.14]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/emallette/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/emallette/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Jul  3 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

pip freeze
ansible==7.7.0
ansible-core==2.14.14
ansible-pylibssh==1.2.2
Babel==2.9.1
bcrypt==4.2.0
cffi==1.14.5
chardet==4.0.0
cockpit @ file:///builddir/build/BUILD/cockpit-311.2/tmp/wheel/cockpit-311.2-py3-none-any.whl
cryptography==36.0.1
dasbus==1.4
dbus-python==1.2.18
decorator==4.4.2
distro==1.5.0
dnspython==2.3.0
file-magic==0.4.0
gpg==1.15.1
gssapi==1.6.9
idna==2.10
iotop==0.6
ipaclient==4.11.0
ipalib==4.11.0
ipaplatform==4.11.0
ipapython==4.11.0
Jinja2==2.11.3
junos-eznc==2.7.1
jwcrypto==0.8
libcomps==0.1.18
lxml==5.3.0
MarkupSafe==1.1.1
ncclient==0.6.15
netaddr==0.8.0
netifaces==0.10.6
nftables==0.1
packaging==20.9
paramiko==3.4.1
perf==0.1
pexpect==4.8.0
ply==3.11
psutil==5.8.0
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyGObject==3.40.1
PyNaCl==1.5.0
pyparsing==2.4.7
pyserial==3.5
PySocks==1.7.1
python-augeas==0.5.0
python-dateutil==2.8.1
python-ldap==3.4.3
python-linux-procfs==0.7.3
python-yubico==1.3.3
pytz==2021.1
pyudev==0.22.0
pyusb==1.0.2
PyYAML==5.4.1
qrcode==6.1
requests==2.25.1
resolvelib==0.5.4
rpm==4.16.1.3
scp==0.15.0
selinux==3.6
sepolicy==3.6
setools==4.4.4
setroubleshoot @ file:///builddir/build/BUILD/setroubleshoot-3.3.32/src
six==1.15.0
sos==4.7.1
SSSDConfig==2.9.4
systemd-python==234
transitions==0.9.2
urllib3==1.26.5
xmltodict==0.13.0
yamlordereddictloader==0.4.2
****

```

OS / Environment
------

```
Hostname: JNBOAR10-CR01
Model: ACX7100-32C
Junos: 23.4R2.14-EVO
Yocto: 3.0.2
Linux Kernel: 5.2.60-yocto-standard-g25b2b83
JUNOS-EVO OS 64-bit [junos-evo-install-acx-f-x86-64-23.4R2.14-EVO]
```

Summary
------
I am unable to gather facts using the device.juniper collection over netconf.  I get much further along with ssh but it also fails and I would prefer to use netconf.

Steps to reproduce
------
```yaml
---
- name: Test NETCONF connectivity with Juniper device
  hosts: juniper
  gather_facts: no
  collections:
    - juniper.device
  tasks:
    - name: Gather basic facts
      juniper.device.facts:
```

# group_vars/juniper.yml
ansible_user: [censored]
ansible_password: [censored]
ansible_connection: netconf
ansible_network_os: junos

[juniper]
# JNBOAR1E-ES01 ansible_host=jnboar1e-es01.diamondstatenetworks.com
JNBOAR1E-ER01 ansible_host=jnboar1e-er01.diamondstatenetworks.com
# JNBOAR1F-ER01 ansible_host=jnboar1f-er01.diamondstatenetworks.com
# JNBOAR10-CR01 ansible_host=jnboar10-cr01.diamondstatenetworks.com

Expected results

```
This is a simple playbook to validate basic functionality because what I wanted to do was failing so I built the most basic playbook.  I just wanted simple facts collection froma single device.
```
Actual results
------

```
ansible-playbook -i hosts.ini test_playbook.yml -vvv
ansible-playbook [core 2.14.14]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/emallette/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/emallette/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.18 (main, Jul  3 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/emallette/ansible/hosts.ini as it did not pass its verify_file() method
script declined parsing /home/emallette/ansible/hosts.ini as it did not pass its verify_file() method
auto declined parsing /home/emallette/ansible/hosts.ini as it did not pass its verify_file() method
yaml declined parsing /home/emallette/ansible/hosts.ini as it did not pass its verify_file() method
Parsed /home/emallette/ansible/hosts.ini inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test_playbook.yml ************************************************************************************************************************************************************************************************************************
1 plays in test_playbook.yml

PLAY [Test NETCONF connectivity with Juniper device] ***********************************************************************************************************************************************************************************************

TASK [Gather basic facts] **************************************************************************************************************************************************************************************************************************
task path: /home/emallette/ansible/test_playbook.yml:8
redirecting (type: connection) ansible.builtin.netconf to ansible.netcommon.netconf
redirecting (type: netconf) ansible.builtin.junos to junipernetworks.junos.junos
<jnboar1e-er01.diamondstatenetworks.com> ESTABLISH LOCAL CONNECTION FOR USER: emallette
<jnboar1e-er01.diamondstatenetworks.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs `"&& mkdir "` echo /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722 `" && echo ansible-tmp-1724002528.1626766-135524-97823641586722="` echo /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722 `" ) && sleep 0'
Using module file /home/emallette/.ansible/collections/ansible_collections/juniper/device/plugins/modules/facts.py
<jnboar1e-er01.diamondstatenetworks.com> PUT /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/tmpj1bdgmms TO /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py
<jnboar1e-er01.diamondstatenetworks.com> EXEC /bin/sh -c 'chmod u+x /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/ /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py && sleep 0'
<jnboar1e-er01.diamondstatenetworks.com> EXEC /bin/sh -c '/usr/bin/python3 /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py && sleep 0'
<jnboar1e-er01.diamondstatenetworks.com> EXEC /bin/sh -c 'rm -f -r /home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py", line 107, in <module>
    _ansiballz_main()
  File "/home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.facts', init_globals=dict(_module_fqn='ansible_collections.juniper.device.plugins.modules.facts', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/modules/facts.py", line 367, in <module>
  File "/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/modules/facts.py", line 309, in main
  File "/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 610, in __init__
  File "/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 742, in fail_json
  File "/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 1213, in close_configuration
AttributeError: 'JuniperJunosModule' object has no attribute '_pyez_conn'
fatal: [JNBOAR1E-ER01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/emallette/.ansible/tmp/ansible-local-135514uat7wlvs/ansible-tmp-1724002528.1626766-135524-97823641586722/AnsiballZ_facts.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.facts', init_globals=dict(_module_fqn='ansible_collections.juniper.device.plugins.modules.facts', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/modules/facts.py\", line 367, in <module>\n  File \"/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/modules/facts.py\", line 309, in main\n  File \"/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 610, in __init__\n  File \"/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 742, in fail_json\n  File \"/tmp/ansible_juniper.device.facts_payload_ojf3_c5c/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 1213, in close_configuration\nAttributeError: 'JuniperJunosModule' object has no attribute '_pyez_conn'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by emallette** [comment]
Issue is with non-descriptive error messages.
